FROM jenkins/jenkins:lts
USER root

RUN apt-get update -qq \
    && apt-get install -qqy apt-transport-https ca-certificates curl \
    && apt-get install -qqy gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg|apt-key add - \
    && apt-key fingerprint 0EBFCD88 \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update -qq \
    && apt-get install -qqy docker-ce \
    && usermod -aG docker jenkins \
    && chown -R jenkins:jenkins $JENKINS_HOME/

VOLUME [$JENKINS_HOME, "/var/run/docker.sock"]
RUN echo "root:12345" | chpasswd
USER jenkins

