FROM ruby:2.6.3

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y libmysqlcppconn-dev cmake build-essential \
                       libswscale-dev libavresample-dev libtbb2 libtbb-dev \
                       libjpeg-dev libpng-dev libtiff-dev libavformat-dev \
                       libpq-dev git wget unzip yasm pkg-config \
                       python-pip python3 python3-pip googletest \
                       imagemagick build-essential mysql-client nodejs \
                       autoconf bison libssl-dev libyaml-dev \
                       libreadline6-dev zlib1g-dev libncurses5-dev \
                       libffi-dev libgdbm3 libgdbm-dev libcurl4-openssl-dev \
                       imagemagick ffmpeg git vim yarn gdb locales \
                       libssl-dev openssh-server mysql-server


RUN pip install numpy
RUN pip3 install numpy

ENV OPENCV_VERSION="3.4.6"
ENV PYTHON2_EXECUTABLE="/usr/bin/python2.7"

RUN wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip \
    && unzip ${OPENCV_VERSION}.zip

RUN mkdir /opencv-${OPENCV_VERSION}/cmake_binary \
    && cd /opencv-${OPENCV_VERSION}/cmake_binary \
    && cmake -DBUILD_TIFF=ON \
      -DBUILD_opencv_java=OFF \
      -DWITH_CUDA=OFF \
      -DENABLE_AVX=ON \
      -DWITH_OPENGL=ON \
      -DWITH_OPENCL=ON \
      -DWITH_IPP=ON \
      -DWITH_TBB=ON \
      -DWITH_EIGEN=ON \
      -DWITH_V4L=ON \
      -DBUILD_TESTS=OFF \
      -DBUILD_PERF_TESTS=OFF \
      -DCMAKE_BUILD_TYPE=RELEASE \
      -DCMAKE_INSTALL_PREFIX=$(python3.5 -c "import sys; print(sys.prefix)") \
      -DPYTHON_EXECUTABLE=$(which python3.5) \
      -DPYTHON_INCLUDE_DIR=$(python3.5 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
      -DPYTHON_PACKAGES_PATH=$(python3.5 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") ..

RUN cd /opencv-${OPENCV_VERSION}/cmake_binary \
    && make install

RUN rm /${OPENCV_VERSION}.zip \
    && rm -r /opencv-${OPENCV_VERSION} \
    && ldconfig

# install boost with -fPIC
RUN wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
RUN tar xvzf boost_1_70_0.tar.gz
WORKDIR boost_1_70_0/
RUN ./bootstrap.sh --prefix=/usr/local
RUN ./b2 -j $(nproc) cxxflags=-fPIC install; exit 0
WORKDIR /
RUN rm -rf /boost_1_70_0**
RUN echo "/usr/local/lib" >> /etc/ld.so.conf.d/local.conf
RUN ldconfig

COPY ssh_key_dev.pub /root/.ssh/authorized_keys

RUN groupadd -g 1000 dev
RUN useradd -r -u 1000 -g dev dev
RUN mkdir /home/dev && chown -R dev.dev /home/dev

# set the locale to en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && dpkg-reconfigure locales \
    && /usr/sbin/update-locale LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apt-get install -y lcov

RUN gem install bundler actioncable -v 5.2.3 actionmailer -v 5.2.3 actionpack -v 5.2.3 actionview -v 5.2.3 active_storage_base64 -v 0.1.4 \
                activejob -v 5.2.3 activemodel -v 5.2.3 activerecord -v 5.2.3 activestorage -v 5.2.3 activesupport -v 5.2.3 \
                addressable -v 2.6.0 archive-zip -v 0.12.0 arel -v 9.0.0 backports -v 3.14.0 bindex -v 0.7.0 bootsnap -v 1.4.4 \
                builder -v 3.2.3 byebug -v 11.0.1 capybara -v 3.18.0 childprocess -v 1.0.1 chromedriver-helper -v 2.1.1 \
                coffee-rails -v 4.2.2 coffee-script -v 2.4.1 coffee-script-source -v 1.12.2 concurrent-ruby -v 1.1.5 crack -v 0.4.3 \
                crass -v 1.0.4 cucumber -v 3.1.2 cucumber-core -v 3.2.1 cucumber-expressions -v 6.0.1 cucumber-rails -v 1.7.0 \
                cucumber-tag_expressions -v 1.1.1 cucumber-wire -v 0.0.1 database_cleaner -v 1.7.0 diff-lcs -v 1.3 docile -v 1.3.1
                erubi -v 1.8.0 execjs -v 2.7.0 ffi -v 1.10.0 gherkin -v 5.1.0 globalid -v 0.4.2 hashdiff -v 0.3.9 i18n -v 1.6.0 \
                io-like -v 0.3.0 jbuilder -v 2.8.0 json -v 2.2.0 listen -v 3.1.5 loofah -v 2.2.3 mail -v 2.7.1 marcel -v 0.3.3 \
                method_source -v 0.9.2 mime-types -v 3.2.2 mime-types-data -v 3.2019.0331 mimemagic -v 0.3.3 mini_magick -v 4.9.3 \
                mini_mime -v 1.0.1 mini_portile2 -v 2.4.0 minitest -v 5.11.3 msgpack -v 1.2.10 multi_json -v 1.13.1 multi_test -v 0.1.2 \
                mysql2 -v 0.5.2 nio4r -v 2.3.1 nokogiri -v 1.10.3 public_suffix -v 3.0.3 puma -v 3.12.1 rack -v 2.0.7 rack-test -v 1.1.0 \
                rails -v 5.2.3 rails-dom-testing -v 2.0.3 rails-html-sanitizer -v 1.0.4 railties -v 5.2.3 rake -v 12.3.2 rb-fsevent -v 0.10.3 \
                rb-inotify -v 0.10.0 regexp_parser -v 1.4.0 rspec -v 3.8.0 rspec-core -v 3.8.0 rspec-expectations -v 3.8.3 rspec-mocks -v 3.8.0 \
                rspec-support -v 3.8.0 ruby_dep -v 1.5.0 rubyzip -v 1.2.2 safe_yaml -v 1.0.5 sass -v 3.7.4 sass-listen -v 4.0.0 sass-rails -v 5.0.7 \
                selenium-webdriver -v 3.142.1 simplecov -v 0.16.1 simplecov-html -v 0.10.2 spring -v 2.0.2 spring-watcher-listen -v 2.0.1 \
                sprockets -v 3.7.2 sprockets-rails -v 3.2.1 thor -v 0.20.3 thread_safe -v 0.3.6 tilt -v 2.0.9 turbolinks -v 5.2.0 \
                turbolinks-source -v 5.2.0 tzinfo -v 1.2.5 uglifier -v 4.1.20 web-console -v 3.7.0 webmock -v 3.5.1 websocket-driver -v 0.7.0 \
                websocket-extensions -v 0.1.3 xpath -v 3.2.0

